name: Gallery CI - debug

on:
 push:
  branches:
   - main-wip

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        cache: 'gradle'
        java-version: 17
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: build debug apk
      run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@v3
      with:
        name: a
        path: app/build/
